---
- name: Ensure PostgreSQL Databases are Present.
  postgresql_db:
    login_host: "{{postgres_host}}"
    login_port: 5432
    login_password: "{{postgres_root_password}}"
    name: "{{database_name}}"
    state: "present"

- name: Ensure PostgreSQL Users are Present.
  postgresql_user:
    login_host: "{{postgres_host}}"
    login_port: 5432
    login_password: "{{postgres_root_password}}"
    name: "{{database_user}}"
    password: "{{database_password}}"
    state: "present"